# Generated by Django 4.0.5 on 2022-07-13 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do livro.', max_length=70)),
                ('publication_date', models.DateField(verbose_name='A data em que o livro foi publicado.')),
                ('isbn', models.CharField(help_text='Numero ISBN do livro.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text='Nomes do contribuidor.', max_length=50)),
                ('last_names', models.CharField(help_text='Sobrenomes do contribuidor.', max_length=50)),
                ('email', models.EmailField(help_text='Email de contto do contribuidor.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(help_text='Email da editora.', max_length=254),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Nome da editora.', max_length=80),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(help_text='Site da editora.'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='O texto da análise.')),
                ('rating', models.IntegerField(help_text='A classificação que o analista concede ao livro.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='A data em que a análise foi criada.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='A data da ultima edição da análise.', null=True)),
                ('book', models.ForeignKey(help_text='O livro referenciado nessa análise.', on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('creator', models.ForeignKey(help_text='O criador da análise.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Autor'), ('CO_AUTHOR', 'Co-Autor'), ('EDITOR', 'Editor')], max_length=20, verbose_name='A função desempenhada pelo cnontribuidor no livro.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor')),
            ],
            options={
                'verbose_name_plural': 'Book Contributors',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='reviews.BookContributor', to='reviews.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher'),
        ),
    ]
